DROP TABLE IF EXISTS public.users_beverages;
DROP TABLE IF EXISTS public.meetings_users;
DROP TABLE IF EXISTS public.meetings_beverages;

DROP TABLE IF EXISTS public.beverages;
DROP TABLE IF EXISTS public.meetings;
DROP TABLE IF EXISTS public.users;



------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(50)NOT NULL UNIQUE,
    user_name character varying(50)NOT NULL UNIQUE,
    password character varying(255)NOT NULL,
    PRIMARY KEY (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.beverages
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) NOT NULL,
    description character varying(255),
    PRIMARY KEY (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.meetings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    address character varying(255) NOT NULL,
    name character varying(100)NOT NULL,
    owner_user_id bigint,
    PRIMARY KEY (id),
    FOREIGN KEY (owner_user_id) REFERENCES public.users (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.users_beverages
(
    user_id bigint NOT NULL,
    beverage_id bigint NOT NULL,
    PRIMARY KEY (user_id, beverage_id),
    FOREIGN KEY (beverage_id) REFERENCES public.beverages (id),
    FOREIGN KEY (user_id) REFERENCES public.users (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.meetings_users
(
    meeting_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (meeting_id, user_id),
    FOREIGN KEY (meeting_id) REFERENCES public.meetings (id),
    FOREIGN KEY (user_id) REFERENCES public.users (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.meetings_beverages
(
    meeting_id bigint NOT NULL,
    beverage_id bigint NOT NULL,
    PRIMARY KEY (meeting_id, beverage_id),
    FOREIGN KEY (beverage_id) REFERENCES public.beverages (id),
    FOREIGN KEY (meeting_id) REFERENCES public.meetings (id)
);

------------------------------------------------------------------------------------------------------------------------



