DROP TABLE IF EXISTS public.users_beverages;
DROP TABLE IF EXISTS public.meetings_users;
DROP TABLE IF EXISTS public.meetings_beverages;
DROP TABLE IF EXISTS public.roles_permissions;
DROP TABLE IF EXISTS public.users_roles;

DROP TABLE IF EXISTS public.permissions;
DROP TABLE IF EXISTS public.roles;
DROP TABLE IF EXISTS public.beverages;
DROP TABLE IF EXISTS public.meetings;
DROP TABLE IF EXISTS public.users;



------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(50)NOT NULL UNIQUE,
    user_name character varying(50)NOT NULL UNIQUE,
    password character varying(255)NOT NULL,
    PRIMARY KEY (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.beverages
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) NOT NULL,
    description character varying(255),
    PRIMARY KEY (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.meetings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date timestamp without time zone NOT NULL,
    address character varying(255) NOT NULL,
    name character varying(100)NOT NULL,
    owner_user_id bigint,
    PRIMARY KEY (id),
    FOREIGN KEY (owner_user_id) REFERENCES public.users (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(30) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.users_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES public.users (id),
    FOREIGN KEY (role_id) REFERENCES public.roles (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.roles_permissions
(
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (permission_id) REFERENCES public.permissions (id) ,
    FOREIGN KEY (role_id) REFERENCES public.roles (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.users_beverages
(
    user_id bigint NOT NULL,
    beverage_id bigint NOT NULL,
    PRIMARY KEY (user_id, beverage_id),
    FOREIGN KEY (beverage_id) REFERENCES public.beverages (id),
    FOREIGN KEY (user_id) REFERENCES public.users (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.meetings_users
(
    meeting_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (meeting_id, user_id),
    FOREIGN KEY (meeting_id) REFERENCES public.meetings (id),
    FOREIGN KEY (user_id) REFERENCES public.users (id)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.meetings_beverages
(
    meeting_id bigint NOT NULL,
    beverage_id bigint NOT NULL,
    PRIMARY KEY (meeting_id, beverage_id),
    FOREIGN KEY (beverage_id) REFERENCES public.beverages (id),
    FOREIGN KEY (meeting_id) REFERENCES public.meetings (id)
);

------------------------------------------------------------------------------------------------------------------------



